### ISSUE TITLE
Exact scale value to reproduce the results in the paper? 

### ISSUE THREAD

**Issue by ryunuri** [yangqy1110/NC-SDEdit#3]
Dear @yangqy1110
Thank you for sharing this work; I appreciate the effort you've put into both the paper and the accompanying code.

I have some questions regarding the implementation details. Specifically, I'm interested in the exact `scale` value used in the `get_low_or_high_fft` function to reproduce the results from the paper.

In the paper, the default threshold frequency value is set to $\nu = 1$ and the Fourier mask is given as:

$$\begin{equation}
\beta_h^\nu =
\begin{cases}
0, & \text{if } r < \nu, \\
1, & \text{otherwise.}
\end{cases}
\end{equation}$$

However, I assume this is not the same as setting `scale=1.0` in the code, as that would create a zero mask and effectively change the update to `e_t = e_t_theta`. Could you please clarify what the default `scale` value should be in `get_low_or_high_fft` to match the settings used in the paper?

**Comment by yangqy1110** [comment]
Your understanding is correct. The terms $\nu$ and `scale` are synonymous. When $\nu$ equals 1, it corresponds to the strongest constraint. The minimization problem can be expressed as: $\min_{\epsilon_{t_0}} ||x^{r}-\hat{x}_0^{t_0}||$. Based on the fixed-point iteration method, we can also derive new iterative formulas, `e_t = e_t_theta`. 

Thank you for your kind words. I hope I was able to assist you effectively. If you have any more questions or need further help, feel free to reach out. Wishing you well too!

**Comment by ryunuri** [comment]
Thank you for your quick and clear response! Your explanation helped clarify my doubts.
Wishing you all the best with your work!
